# Generated by Django 2.2.2 on 2019-06-24 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='address',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='birth_day',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='nation_code',
            field=models.CharField(blank=True, default='1234567890', max_length=10),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='sex',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MS', 'Ms.')], default='MR', max_length=3),
        ),
    ]
