# Generated by Django 2.2.2 on 2019-06-25 13:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('holter', '0002_auto_20190624_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending_physician', models.CharField(blank=True, default='', max_length=100)),
                ('admission_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_of_discharge', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('patient_history', models.TextField(blank=True, default='', max_length=1000)),
                ('primary_dignosis', models.TextField(blank=True, default='', max_length=1000)),
                ('final_dignosis', models.TextField(blank=True, default='', max_length=1000)),
                ('medical_surgical_procedures', models.TextField(blank=True, default='', max_length=1000)),
                ('cause_of_date', models.TextField(blank=True, default='', max_length=1000)),
                ('patient_condition_discharge', models.TextField(blank=True, default='', max_length=1000)),
                ('recommendtions_discharge', models.TextField(blank=True, default='', max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='holter.Profiles')),
            ],
        ),
    ]
